---
# Example events config

- id: example-event
  name: Example Event
  description: |
    An example event.
  date: 2024-07-04
  open: true
  visible: true

  # Registration options
  registration_options:
    - id: standard
      name: Standard
      description: Standard registration level
    - id: vip
      name: VIP
      description: VIP upgrade

  # Interviews available for adding a registration
  add_interviews:
    - id: new-registration
      name: New Registration
      when: true

  # Interviews available for changing a registration
  change_interviews:
    - id: update-registration
      name: Update Registration
      when: true

  # Basic pricing rules
  pricing_rules:
    - name: Standard Registration
      description: Standard registration level.
      price: 5000
      modifiers:
        - type_id: early-bird
          name: Early Bird Discount
          amount: -500
          when: true
      when:
        - "'standard' in added_option_ids"

    - name: VIP Upgrade
      description: VIP upgrade.
      price: 2500
      when:
        - "'vip' in added_option_ids"

    # To prevent incorrectly pricing a cart, every change must result in at
    # least one line item. The server will raise an error if a change results in
    # no line items.
    - name: Name Change
      description: Update registration information.
      price: 0
      when:
        - registration.old_data.state == "created"
        - or:
            - registration.new_data.first_name != registration.old_data.first_name
            - registration.new_data.last_name != registration.old_data.last_name

  # Display options
  display_options:
    # Registration display template in the self-service view.
    registration:
      title: "{{ registration.display_name }}"
      subtitle: >-
        {% if "vip" in registration.option_ids %}
          VIP
        {% else %}
          Standard
        {% endif %}
      description: |
        Example registration.
