---
# Webhooks container configuration

# Email webhooks
email:
  # Path to the template directory
  template_path: /config/templates/email

  # What to use to send mail: null | mock | smtp | mailgun
  use: mock

  # The default From address.
  email_from: Example <example@example.com>

  # Settings for using SMTP
  # smtp:

  #   # The server and port
  #   server: smtp.example.com
  #   port: 587

  #   username: you@example.com
  #   password: password

  #   # null, ssl, or starttls
  #   tls: starttls

  # Settings for using Mailgun
  # mailgun:
  #   domain: example.com
  #   api_key: api_key
