"""Add email auth code table

Revision ID: 34225d7355cf
Revises: dacb9b683ce1
Create Date: 2023-07-02 15:13:08.025890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34225d7355cf'
down_revision = 'dacb9b683ce1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_auth',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('num_sent', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_email_auth'))
    )
    op.create_index('uq_email_auth_lower_email', 'email_auth', [sa.text("lower('email')")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_email_auth_lower_email', table_name='email_auth')
    op.drop_table('email_auth')
    # ### end Alembic commands ###
